services:
  book:
    image: "book:0.1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
    environment:
      MYSQL_NAME: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
    networks:
      - library-net
    depends_on: 
      mysql: 
        condition: service_healthy                
  mysql:
    image: "mysql:latest"
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysql" ,"--user=${MYSQL_USER}", "--password=${MYSQL_PWD}"]
      timeout: 20s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
        reservations:
          cpus: '1.0'
          memory: 2048M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: books
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - library-net
networks:
  library-net: {}
volumes:
  mysql: {}