apiVersion: apps/v1
kind: Deployment
metadata:
  name: book #Deployment name
  labels:
    app: book #label to find the respective pods to manage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template: #template for the replica/pod specification
    metadata:
      labels:
        app: book #label for the corresponding app
    spec: 
      containers:
      - name: book #container name
        image: kkritikos/book-data-rest:0.1 #container image
        ports:
        - containerPort: 30000 #container port
        env: #get environment vars from specific secret
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               name: user-secret
               key: username
         - name: MYSQL_PWD
           valueFrom:
             secretKeyRef:
               name: user-secret
               key: password
         - name: MYSQL_NAME #pass previous environment vars as system properties to tomcat
           value: "mysql"
         - name: SERVER_PORT
           value: "30000"
        resources:
            requests:
                memory: "512Mi"
                cpu: "500m"
            limits:
                memory: "1024Mi"
                cpu: "2000m"